# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AI Tools & Prompt Engineering for Data Science
author: Sky Sheng

# Information about where the book exists on the web
repository:
  url: https://github.com/skysheng7/ai_tools_playground
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# MyST extensions for enhanced markdown support
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist