# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AI tools playground
author: Sky Sheng
logo: logo.png  # Placeholder - you can add your logo later

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/skysheng7/ai_tools_playground
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

# Citation style configuration
sphinx:
  config:
    bibtex_reference_style: author_year

# MyST extensions for enhanced markdown support
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist