# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: AI Tools & Prompt Engineering for Data Science
author: Sky Sheng
copyright: "2025"
only_build_toc_files: true # only build the files listed under _toc.yml
logo: images/logo1.png

# Exclude directories and files from build
exclude_patterns:
  - .virtual_documents/**
  - .ipynb_checkpoints/**
  - _build/**
  - .github/**
  - .cursor/**

# Information about where the book exists on the web
repository:
  url: https://github.com/skysheng7/ai_tools_playground
  branch: main

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

# MyST extensions for enhanced markdown support
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: ai_tools_playground.tex

# add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references/references.bib

# For citation style
sphinx:
  config:
    bibtex_reference_style: author_year